---
- name: Apache installation,enable,start the service
  hosts: dev
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest

    - name: start the service of apache
      systemd:
        state: started
        name: httpd
    
    - name: enable httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
        masked: no