---
all:
  hosts: #list of ungrouped hosts
  children: #all custom groups
    dev: #group name
      hosts: #list of dev hosts
        host1: #host name
          ansible_host: "10.108.0.3" #host1 address
          ansible_port: "55500" #ssh port
        host2:
          ansible_host: "10.108.0.4"
        host3: #host name of Ubuntu VM
          ansible_host: "10.108.0.5"
          ansible_port: "55500"
        
